# Real-Time Gesture Detection with envisionhgdetector (envisionhgdetector version 2.0.0+)

<br>
<div align="center">Wim Pouw (wim.pouw@donders.ru.nl), Bosco Yung, Sharjeel Shaikh, James Trujillo, Gerard de Melo, Babajide Owoyele (Babajide.Owoyele@hpi.de) </div>
<img src="Images/envisionboxlogo20.png" alt="isolated" width="300"/>

<img src="Images/ex.gif"  width="300"/>

## Info
The envisionhgdetector package (version 2.0.0+) includes advanced real-time gesture detection capabilities using the Light Gradient Boosting Machine (LGBM) model. This enables immediate gesture recognition from webcam feeds, making it suitable for interactive applications, live demonstrations, and real-time analysis workflows.
The real-time inference system maintains the exact same 5-frame temporal window (0.2 seconds) used during training, implemented through rolling buffers that continuously update as new frames arrive from the webcam feed. The system processes frames at 25-30 FPS and generates immediate predictions without waiting for future frames, while preserving the temporal dynamics and spatial relationships the model learned during training.

## Light Gradient Boosting Machine (available in Version 2+)
Here we trained on the SAGA, SAGA+, ECOLANG, MULTISIMO, Zhubo, and the TED M3D dataset. We originally use 23 upper body landmarks (69 features: 23 landmarks × 3 coordinates) where we make use of world_pose_landmarks, which are the 3D coordinates of the upper body landmarks in meters centered around the hip. We then take the following features selected from an upper body keypoints (x, y, z data) -> 18 features: Current upper arm pose (6 key joints × 3 coordinates) + 18 Current velocities arm pose + 2 overall wrist speed features (left and right) + 6 features: Range of motion over window for arms + 18 features: Finger positions (9 per hand: pinky, index, thumb × 3 coords) + 6 features: Finger shape distances (inter-finger distances) + 12 features: Padding to reach 80. For training we take a size of 5 frames (0.2 seconds), with a stride of 1 frame (0.04 seconds), and with a 5-fold cross-validation stratified for datasets that have enough data for each class. We train a Light Gradient Boosting Machine (LGBM) model as this is a very fast and efficient model. The labels that it detects is based on gesture vs. no gesture (which now also includes self-adaptors, or non-communicative "move" actions), which should avoid false-positive gesture detection a bit (e.g., a nose-scratching movement being detected as a gesture).

We then use this model for inferences. Now also enabling real time tracking. Real-time inference operates with the same 5-frame window but implements it through rolling buffers that continuously update as new frames arrive from the webcam feed. We discuss the real-time inference in this notebook.

## Preprint
For more information we will refer to a preprint here: [https://osf.io/psg5f_v1](https://osf.io/psg5f_v1). The preprint will be updated soon to accomodate the latest version of the package (version > 2.0.0).

## Package info
https://pypi.org/project/envisionhgdetector/

### What does envisionhgdetector do
* It tracks upper body, hands, and face landmarks using MediaPipe.
* Convolutional Neural Network (CNN) model makes an inference based on 25 frames of data, whether it labels no gesture (default implicit label), gesture (label: Gesture), or some kind of movement that is not a gesture (label: Move).
* Light Gradient Boosting Machine (LGBM) model makes an inference based on 5 frames of data, whether it labels no gesture (default implicit label), gesture (label: Gesture).
* It outputs a labeled video, an ELAN file, a confidence timeseries, and a gesture segment list (with labels and start and end times).
* It then allows you to retrack the gestures with metric pose world landmarks, which allows us to compare gestures as theire positions are given in meters rather than pixels
* Then we compute kinematic features, produced DTW distances between the gestures
* Then we create a visualization dashboard that summarizes the gesture kinematics
* **It enables real-time tracking and inference, allowing for immediate gesture detection and analysis.** (which is discussed here)

## Installation and running the demo
It is best to install in a conda environment. 

```Bash
conda create -n envision python = 3.9
conda activate envision
cd [./usingenvisionhgdetector] # cd to your repo
# Then proceed: 
pip install -r requirements.txt
python demo_webcam_realtime.py
```

## Citation
If you use this package, please cite:
* Pouw, W., Yung, B., Shaikh, S., Trujillo, J., Rueda-Toicen, A., de Melo, G., & Owoyele, B. (2024). envisionhgdetector: Hand Gesture Detection Using a Convolutional Neural Network (Version 0.0.5.2) [Computer software]. https://pypi.org/project/envisionhgdetector/

### Citations for the packages and datasets, and work that this builds on
Original Noddingpigeon Training code:
* Yung, B. (2022). Nodding Pigeon (Version 0.6.0) [Computer software]. https://github.com/bhky/nodding-pigeon

Zhubo dataset (used for training):
* Bao, Y., Weng, D., & Gao, N. (2024). Editable Co-Speech Gesture Synthesis Enhanced with Individual Representative Gestures. Electronics, 13(16), 3315.

SAGA dataset (used for training)
* Lücking, A., Bergmann, K., Hahn, F., Kopp, S., & Rieser, H. (2010). The Bielefeld speech and gesture alignment corpus (SaGA). In LREC 2010 workshop: Multimodal corpora–advances in capturing, coding and analyzing multimodality.

TED M3D:
* Rohrer, Patrick. A temporal and pragmatic analysis of gesture-speech association: A corpus-based approach using the novel MultiModal MultiDimensional (M3D) labeling system. Diss. Nantes Université; Universitat Pompeu Fabra (Barcelone, Espagne), 2022.

ECOLANG dataset (used for training):
Gu, Y., Donnellan, E., Grzyb, B., Brekelmans, G., Murgiano, M., Brieke, R., ... & Vigliocco, G. (2025). The ECOLANG Multimodal Corpus of adult-child and adult-adult Language. Scientific data, 12(1), 89.

MULTISIMO dataset (used for training):
Koutsombogera, M., & Vogel, C. (2017, November). The MULTISIMO multimodal corpus of collaborative interactions. In Proceedings of the 19th ACM International Conference on Multimodal Interaction (pp. 502-503).

MediaPipe:
* Lugaresi, C., Tang, J., Nash, H., McClanahan, C., Uboweja, E., Hays, M., ... & Grundmann, M. (2019). MediaPipe: A framework for building perception pipelines. arXiv preprint arXiv:1906.08172.

DTW:
* Giorgino, T. (2009). Computing and visualizing dynamic time warping alignments in R: the dtw package. Journal of statistical Software, 31, 1-24.

Soft-DTW:
* Cuturi, M., & Blondel, M. (2017, July). Soft-dtw: a differentiable loss function for time-series. In International conference on machine learning (pp. 894-903). PMLR.

Creating Elan Files (and a good paper on classification on gestures)
* Ienaga, Naoto, Alice Cravotta, Kei Terayama, Bryan W. Scotney, Hideo Saito, and M. Grazia Busa. "Semi-automation of gesture annotation by machine learning and human collaboration." Language Resources and Evaluation 56, no. 3 (2022): 673-700.

Kinematic features & DTW
* Trujillo, J. P., Vaitonyte, J., Simanova, I., & Özyürek, A. (2019). Toward the markerless and automatic analysis of kinematic features: A toolkit for gesture and movement research. Behavior Research Methods, 51, 769-777.
* Pouw, W., & Dixon, J. A. (2020). Gesture networks: Introducing dynamic time warping and network analysis for the kinematic study of gesture ensembles. Discourse Processes, 57(4), 301-319.

# Some notes on the demo python code
For this tutorial, I have two videos that I would like to segment for hand gestures. They all live in the folder: './videos_to_label/'

In [ ]:
import os
import glob as glob

videofoldertoday = './videos_to_label/'
outputfolder = './output/'

In [16]:
import glob
from IPython.display import Video

# List all videos in the folder
videos = glob.glob(videofoldertoday + '*.mp4')
# Display single video
Video(videos[0], embed=True, width=200)

In [25]:
import pandas as pd
import os
import glob as glob
# lets list the output
outputfiles = glob.glob(outputfolder + '/*')
for file in outputfiles:
    print(os.path.basename(file))

# load one of the predictions
csvfilessegments = glob.glob(outputfolder + '/*segments.csv')
df = pd.read_csv(csvfilessegments[0])
df.head()

analysis
app.py
assets
gesture_segments
labeled_test_female.mp4
labeled_test_male.mp4
retracked
test_female.mp4.eaf
test_female.mp4_features.npy
test_female.mp4_predictions.csv
test_female.mp4_segments.csv
test_male.mp4.eaf
test_male.mp4_features.npy
test_male.mp4_predictions.csv
test_male.mp4_segments.csv

   start_time   end_time  labelid    label  duration
0    0.133466   1.234563        1  Gesture  1.101097
1    2.335660   3.236558        2  Gesture  0.900898
2    3.803790   4.137455        3  Gesture  0.333666
3    4.437755   6.539849        4  Gesture  2.102094
4    7.674312  11.177803        5  Gesture  3.503490

## Lets assess the labeled video data

In [26]:
from moviepy import VideoFileClip
videoslabeled = glob.glob(outputfolder + '/*.mp4')

# need to rerender
clip = VideoFileClip(videoslabeled[0])
clip.write_videofile("./labeled_test_female.mp4")
Video("./labeled_test_female.mp4", embed=True)

Processing frames:  27%|██▋       | 100/366 [04:53<00:08, 31.63it/s]

MoviePy - Building video ./labeled_test_female.mp4.
MoviePy - Writing video ./labeled_test_female.mp4

Processing frames:  27%|██▋       | 100/366 [04:54<00:08, 31.63it/s]

MoviePy - Done !
MoviePy - video ready ./labeled_test_female.mp4

# STEP 2: Segment the gesture videos
We have some further functionality in the package that will help in further analysis. Often we want to cut the videos by each gesture event, as these are the moments that were interested in. Therefore in the packages' utils (utilities library) we have a further functionality that takes each labeled video, and then generates subclips per gesture event, and also extracts the normalized features on which the gesture classifications were based. In the output folder there will be a new folder created called output/gesture_segments, with for each video subclips of each gesture and their features.

In [27]:
# Step 2: Cut videos into segments
from envisionhgdetector import utils
segments = utils.cut_video_by_segments(outputfolder)

Processing frames:  27%|██▋       | 100/366 [05:09<00:08, 31.63it/s]

MoviePy - Building video d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_female.mp4\test_female.mp4_segment_1_Gesture_0.13_1.23.mp4.
MoviePy - Writing video d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_female.mp4\test_female.mp4_segment_1_Gesture_0.13_1.23.mp4

Processing frames:  27%|██▋       | 100/366 [05:09<00:08, 31.63it/s]

MoviePy - Done !
MoviePy - video ready d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_female.mp4\test_female.mp4_segment_1_Gesture_0.13_1.23.mp4
Created segment and features: test_female.mp4_segment_1_Gesture_0.13_1.23.mp4
Proc not detected
MoviePy - Building video d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_female.mp4\test_female.mp4_segment_2_Gesture_2.34_3.24.mp4.
MoviePy - Writing video d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_female.mp4\test_female.mp4_segment_2_Gesture_2.34_3.24.mp4

Processing frames:  27%|██▋       | 100/366 [05:09<00:08, 31.63it/s]

MoviePy - Done !
MoviePy - video ready d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_female.mp4\test_female.mp4_segment_2_Gesture_2.34_3.24.mp4
Created segment and features: test_female.mp4_segment_2_Gesture_2.34_3.24.mp4
Proc not detected

Processing frames:  27%|██▋       | 100/366 [05:09<00:08, 31.63it/s]

MoviePy - Building video d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_female.mp4\test_female.mp4_segment_3_Gesture_3.80_4.14.mp4.
MoviePy - Writing video d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_female.mp4\test_female.mp4_segment_3_Gesture_3.80_4.14.mp4

Processing frames:  27%|██▋       | 100/366 [05:09<00:08, 31.63it/s]

MoviePy - Done !
MoviePy - video ready d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_female.mp4\test_female.mp4_segment_3_Gesture_3.80_4.14.mp4
Created segment and features: test_female.mp4_segment_3_Gesture_3.80_4.14.mp4
Proc not detected
MoviePy - Building video d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_female.mp4\test_female.mp4_segment_4_Gesture_4.44_6.54.mp4.
MoviePy - Writing video d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_female.mp4\test_female.mp4_segment_4_Gesture_4.44_6.54.mp4

Processing frames:  27%|██▋       | 100/366 [05:09<00:08, 31.63it/s]

MoviePy - Done !
MoviePy - video ready d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_female.mp4\test_female.mp4_segment_4_Gesture_4.44_6.54.mp4
Created segment and features: test_female.mp4_segment_4_Gesture_4.44_6.54.mp4
Proc not detected

Processing frames:  27%|██▋       | 100/366 [05:09<00:08, 31.63it/s]

MoviePy - Building video d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_female.mp4\test_female.mp4_segment_5_Gesture_7.67_11.18.mp4.
MoviePy - Writing video d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_female.mp4\test_female.mp4_segment_5_Gesture_7.67_11.18.mp4

Processing frames:  27%|██▋       | 100/366 [05:09<00:08, 31.63it/s]

MoviePy - Done !
MoviePy - video ready d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_female.mp4\test_female.mp4_segment_5_Gesture_7.67_11.18.mp4
Created segment and features: test_female.mp4_segment_5_Gesture_7.67_11.18.mp4
Completed processing segments for test_female.mp4

Processing frames:  27%|██▋       | 100/366 [05:09<00:08, 31.63it/s]

MoviePy - Building video d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_male.mp4\test_male.mp4_segment_1_Gesture_0.17_3.64.mp4.
MoviePy - Writing video d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_male.mp4\test_male.mp4_segment_1_Gesture_0.17_3.64.mp4

Processing frames:  27%|██▋       | 100/366 [05:10<00:08, 31.63it/s]

MoviePy - Done !
MoviePy - video ready d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_male.mp4\test_male.mp4_segment_1_Gesture_0.17_3.64.mp4
Created segment and features: test_male.mp4_segment_1_Gesture_0.17_3.64.mp4
Proc not detected
MoviePy - Building video d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_male.mp4\test_male.mp4_segment_2_Gesture_5.00_5.81.mp4.
MoviePy - Writing video d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_male.mp4\test_male.mp4_segment_2_Gesture_5.00_5.81.mp4

Processing frames:  27%|██▋       | 100/366 [05:10<00:08, 31.63it/s]

MoviePy - Done !
MoviePy - video ready d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_male.mp4\test_male.mp4_segment_2_Gesture_5.00_5.81.mp4
Created segment and features: test_male.mp4_segment_2_Gesture_5.00_5.81.mp4
Proc not detected
MoviePy - Building video d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_male.mp4\test_male.mp4_segment_3_Gesture_8.98_9.78.mp4.
MoviePy - Writing video d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_male.mp4\test_male.mp4_segment_3_Gesture_8.98_9.78.mp4

Processing frames:  27%|██▋       | 100/366 [05:10<00:08, 31.63it/s]

MoviePy - Done !
MoviePy - video ready d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_male.mp4\test_male.mp4_segment_3_Gesture_8.98_9.78.mp4
Created segment and features: test_male.mp4_segment_3_Gesture_8.98_9.78.mp4
Proc not detected
MoviePy - Building video d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_male.mp4\test_male.mp4_segment_4_Gesture_12.01_12.35.mp4.
MoviePy - Writing video d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_male.mp4\test_male.mp4_segment_4_Gesture_12.01_12.35.mp4

Processing frames:  27%|██▋       | 100/366 [05:10<00:08, 31.63it/s]

MoviePy - Done !
MoviePy - video ready d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_male.mp4\test_male.mp4_segment_4_Gesture_12.01_12.35.mp4
Created segment and features: test_male.mp4_segment_4_Gesture_12.01_12.35.mp4
Proc not detected
MoviePy - Building video d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_male.mp4\test_male.mp4_segment_5_Gesture_12.71_13.01.mp4.
MoviePy - Writing video d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_male.mp4\test_male.mp4_segment_5_Gesture_12.71_13.01.mp4

Processing frames:  27%|██▋       | 100/366 [05:10<00:08, 31.63it/s]

MoviePy - Done !
MoviePy - video ready d:\Research_projects\usingenvisionhgdetector\output\gesture_segments\test_male.mp4\test_male.mp4_segment_5_Gesture_12.71_13.01.mp4
Created segment and features: test_male.mp4_segment_5_Gesture_12.71_13.01.mp4
Completed processing segments for test_male.mp4

# STEP 3: Retrack the gesture videos 
If we want to do kinematic analysis on the gestures, an issue is that we are working in pixel units. Mediapipe allows for tracking body keypoints in metric-estimated units. We need this for our kinematic analysis. Next we generate this. We also generate the tracked videos, so we can do further quality checking.

In [28]:
# Step 3: Create paths
gesture_segments_folder = os.path.join(outputfolder, "gesture_segments")
retracked_folder = os.path.join(outputfolder, "retracked")
analysis_folder = os.path.join(outputfolder, "analysis")

print(f"\nLooking for segments in: {gesture_segments_folder}")
if os.path.exists(gesture_segments_folder):
    segment_files = [f for f in os.listdir(gesture_segments_folder) if f.endswith('.mp4')]
    print(f"Found {len(segment_files)} segment files")
else:
    print("Gesture segments folder not found!")

# Step 3: Retrack gestures with world landmarks
print("\nStep 4: Retracking gestures...")
tracking_results = detector.retrack_gestures(
    input_folder=gesture_segments_folder,
    output_folder=retracked_folder
)
print(f"Tracking results: {tracking_results}")

Looking for segments in: d:\Research_projects\usingenvisionhgdetector\output\gesture_segments
Found 2 segment files

Step 4: Retracking gestures...
Processing test_female.mp4_segment_1_Gesture_0.13_1.23
Processing test_female.mp4_segment_1_Gesture_0.50_1.07
Processing test_female.mp4_segment_2_Gesture_2.34_3.24
Processing test_female.mp4_segment_2_Gesture_2.37_3.24
Processing test_female.mp4_segment_3_Gesture_3.80_4.14
Processing test_female.mp4_segment_3_Gesture_4.87_6.54
Processing test_female.mp4_segment_4_Gesture_4.44_6.54
Processing test_female.mp4_segment_4_Gesture_8.01_11.18
Processing test_female.mp4_segment_5_Gesture_7.67_11.18
Processing test_male.mp4_segment_1_Gesture_0.17_3.64
Processing test_male.mp4_segment_1_Gesture_0.23_3.37
Processing test_male.mp4_segment_2_Gesture_5.00_5.81
Processing test_male.mp4_segment_2_Gesture_5.14_5.47
Processing test_male.mp4_segment_3_Gesture_8.98_9.78
Processing test_male.mp4_segment_3_Gesture_9.21_9.44
Processing test_male.mp4_segment_4_Gesture_12.01_12.35
Processing test_male.mp4_segment_5_Gesture_12.71_13.01
Successfully retracked 17 gestures
Tracking results: {'tracked_folder': 'd:\\Research_projects\\usingenvisionhgdetector\\output\\retracked\\tracked_videos', 'landmarks_folder': 'd:\\Research_projects\\usingenvisionhgdetector\\output\\retracked'}

In [29]:
# lets show the new tracked videos
videoslabeled = glob.glob(outputfolder + '/retracked/tracked_videos/*.mp4')

# need to rerender
clip = VideoFileClip(videoslabeled[0])
clip.write_videofile("./retracked.mp4")
Video("./retracked.mp4", embed=True)

Processing frames:  27%|██▋       | 100/366 [05:57<00:08, 31.63it/s]

MoviePy - Building video ./retracked.mp4.
MoviePy - Writing video ./retracked.mp4

Processing frames:  27%|██▋       | 100/366 [05:57<00:08, 31.63it/s]

MoviePy - Done !
MoviePy - video ready ./retracked.mp4

# Step 4: Compute DTW and create visualization

The next big step is that we are going to compute a dissimilarity measure using DTW of all gesture comparisons. We also create a dimensionally reduced version of the distance matrix using UMAP, which we use for the visualization. This we save in a distance matrix in the analysis folder. We also create for each gesture a kinematic feature list (such as max speed, max acceleration, McNeillian space, vertical height etc.). This will also be saved in the analysis folder.

In [30]:
analysis_results = detector.analyze_dtw_kinematics(
        landmarks_folder=tracking_results["landmarks_folder"],
        output_folder=analysis_folder
    )
print(f"Analysis results: {analysis_results}")

Computing DTW distances and kinematic features...
Debug: Landmarks shape is (27, 33, 3)
Debug: Extracting keypoint left_shoulder at index 11
Debug: Data for keypoint left_shoulder: [[-0.01253113 -0.15865568 -0.20847737]
 [-0.02206566 -0.1637331  -0.20919059]
 [-0.02588071 -0.16455665 -0.20647565]
 [-0.02721137 -0.16498245 -0.20574339]
 [-0.0271097  -0.16435516 -0.20415828]
 [-0.02688548 -0.16411392 -0.2037665 ]
 [-0.02694649 -0.16423135 -0.20400908]
 [-0.0269152  -0.16263086 -0.19994318]
 [-0.02735054 -0.15826782 -0.18878716]
 [-0.02884777 -0.15717971 -0.18382827]
 [-0.02927131 -0.15754034 -0.18408734]
 [-0.02922137 -0.15741007 -0.18355046]
 [-0.0275787  -0.15729297 -0.18478498]
 [-0.02555329 -0.15670206 -0.18541935]
 [-0.02009743 -0.15453026 -0.18590265]
 [-0.01938074 -0.15509324 -0.18844856]
 [-0.01700102 -0.15458861 -0.18990666]
 [-0.01166029 -0.15056393 -0.18591838]
 [-0.01140473 -0.14966641 -0.18492638]
 [-0.01097534 -0.14826784 -0.18203222]
 [-0.01000888 -0.14511559 -0.17587313]
 [-0.00858346 -0.14457437 -0.17607759]
 [-0.00625709 -0.14354695 -0.17629851]
 [-0.00618033 -0.1436478  -0.17664403]
 [-0.00603194 -0.14467477 -0.17925296]
 [-0.00591344 -0.14455273 -0.17911835]
 [-0.00530504 -0.14413149 -0.17873914]]
Debug: Extracting keypoint left_elbow at index 13
Debug: Data for keypoint left_elbow: [[ 0.07959582 -0.06759106 -0.16016205]
 [ 0.07170035 -0.06810858 -0.15198552]
 [ 0.06974393 -0.06450399 -0.14103116]
 [ 0.06876885 -0.06453211 -0.13995829]
 [ 0.06873255 -0.06348542 -0.13741908]
 [ 0.06854565 -0.06356338 -0.13742415]
 [ 0.06745043 -0.06455299 -0.13876141]
 [ 0.06725529 -0.06206706 -0.13212817]
 [ 0.06735007 -0.05752157 -0.12095725]
 [ 0.06680386 -0.05488566 -0.11323541]
 [ 0.06659841 -0.0542713  -0.11072222]
 [ 0.06679631 -0.05439415 -0.1099307 ]
 [ 0.06801369 -0.05452455 -0.11048096]
 [ 0.06991902 -0.0526426  -0.10662494]
 [ 0.07414089 -0.05013662 -0.10471256]
 [ 0.07510219 -0.04881516 -0.10237751]
 [ 0.07776237 -0.04800124 -0.10299098]
 [ 0.08232058 -0.04187406 -0.09286774]
 [ 0.08371015 -0.03855927 -0.08731417]
 [ 0.08531263 -0.03475895 -0.07974586]
 [ 0.0868509  -0.0344164  -0.08160533]
 [ 0.08873943 -0.03475343 -0.08485401]
 [ 0.09174972 -0.03523211 -0.09021497]
 [ 0.09148548 -0.03650976 -0.09368394]
 [ 0.09129727 -0.03736199 -0.09591134]
 [ 0.09146525 -0.03648492 -0.09431284]
 [ 0.09140334 -0.03614369 -0.09348087]]
Debug: Extracting keypoint left_wrist at index 15
Debug: Data for keypoint left_wrist: [[ 0.06917393 -0.04094112 -0.14500784]
 [ 0.0663928  -0.03244119 -0.12147486]
 [ 0.06603846 -0.0242079  -0.10135047]
 [ 0.06551454 -0.02556741 -0.10402343]
 [ 0.06586304 -0.02432264 -0.10139869]
 [ 0.06580184 -0.02472596 -0.10225867]
 [ 0.065514   -0.02567862 -0.10422769]
 [ 0.06635296 -0.02133426 -0.09447926]
 [ 0.06712424 -0.01602745 -0.08262581]
 [ 0.06770393 -0.01126006 -0.07186785]
 [ 0.06776204 -0.00871123 -0.06492904]
 [ 0.06837487 -0.00838538 -0.06381661]
 [ 0.07100746 -0.00720749 -0.06274225]
 [ 0.07594922 -0.00189801 -0.05331186]
 [ 0.08229659  0.00145116 -0.05024542]
 [ 0.08319964  0.00396109 -0.04433156]
 [ 0.08595976  0.00329713 -0.04794801]
 [ 0.09228677  0.01105639 -0.03578243]
 [ 0.09485999  0.01910705 -0.02289072]
 [ 0.09516411  0.02332555 -0.01315384]
 [ 0.09427813  0.02003636 -0.02080688]
 [ 0.09288694  0.01450784 -0.03261649]
 [ 0.09250769  0.00809038 -0.04754886]
 [ 0.09274209  0.00800774 -0.04884289]
 [ 0.09272132  0.00803723 -0.0490993 ]
 [ 0.09324014  0.01059385 -0.04378611]
 [ 0.09338516  0.01119395 -0.04249093]]
Debug: Extracting keypoint right_shoulder at index 12
Debug: Data for keypoint right_shoulder: [[-0.23463763 -0.26478795 -0.21368774]
 [-0.23625878 -0.26445481 -0.21066304]
 [-0.23741883 -0.26319082 -0.20594555]
 [-0.23759627 -0.26289048 -0.20487785]
 [-0.23759959 -0.2626157  -0.20391775]
 [-0.23776247 -0.26295702 -0.20415298]
 [-0.23784474 -0.26318669 -0.20452567]
 [-0.23808712 -0.26239978 -0.20169367]
 [-0.23878508 -0.25849957 -0.19072625]
 [-0.23955226 -0.25721395 -0.18581082]
 [-0.24088635 -0.25809126 -0.18595377]
 [-0.24146425 -0.2577574  -0.18376015]
 [-0.24139319 -0.25859857 -0.18510016]
 [-0.24097924 -0.25901626 -0.18609042]
 [-0.23706214 -0.25830258 -0.18812337]
 [-0.23666484 -0.25978362 -0.19206682]
 [-0.23542935 -0.26047467 -0.19496867]
 [-0.23192744 -0.25786467 -0.19229713]
 [-0.23003763 -0.25528372 -0.19033183]
 [-0.22812093 -0.25315926 -0.18756724]
 [-0.22611415 -0.24948884 -0.1817974 ]
 [-0.22496703 -0.24886532 -0.18172926]
 [-0.22346647 -0.24833749 -0.18201699]
 [-0.22311942 -0.24842627 -0.18263608]
 [-0.22241114 -0.24913368 -0.18504578]
 [-0.22216093 -0.24883566 -0.18464185]
 [-0.22152449 -0.24838471 -0.18419176]]
Debug: Extracting keypoint right_elbow at index 14
Debug: Data for keypoint right_elbow: [[-0.18595295 -0.17384276 -0.15398164]
 [-0.18961948 -0.17188233 -0.14345009]
 [-0.19138686 -0.16884065 -0.13325282]
 [-0.19169124 -0.16855397 -0.13212977]
 [-0.19169949 -0.16833879 -0.13141221]
 [-0.19163592 -0.16848036 -0.13168552]
 [-0.19166745 -0.16902011 -0.13295984]
 [-0.19125523 -0.1659545  -0.12554619]
 [-0.19109456 -0.16170942 -0.114986  ]
 [-0.19131463 -0.16049066 -0.11149234]
 [-0.19231565 -0.159514   -0.10733541]
 [-0.19302437 -0.16007837 -0.10742537]
 [-0.19312963 -0.16164144 -0.1103494 ]
 [-0.18997704 -0.1607798  -0.11148678]
 [-0.18383204 -0.1586612  -0.11264418]
 [-0.18025362 -0.15764546 -0.11654962]
 [-0.17764231 -0.15817876 -0.12229523]
 [-0.17317371 -0.15641781 -0.12322728]
 [-0.17304807 -0.16032541 -0.13509163]
 [-0.17339001 -0.16090515 -0.13609131]
 [-0.17349597 -0.16076343 -0.13593138]
 [-0.17429126 -0.1651465  -0.14561265]
 [-0.1738306  -0.16646463 -0.14911441]
 [-0.17390874 -0.1674272  -0.1513356 ]
 [-0.17301753 -0.16823617 -0.15446579]
 [-0.17122035 -0.16627988 -0.15197723]
 [-0.16844498 -0.16448112 -0.15072247]]
Debug: Extracting keypoint right_wrist at index 16
Debug: Data for keypoint right_wrist: [[-0.11854137 -0.13270756 -0.17663706]
 [-0.12276455 -0.12392725 -0.14947093]
 [-0.12453143 -0.11917955 -0.13520943]
 [-0.12502373 -0.11950609 -0.13507313]
 [-0.12493455 -0.11937211 -0.13469882]
 [-0.12499096 -0.11984558 -0.13562309]
 [-0.12512809 -0.12092866 -0.13804294]
 [-0.12508718 -0.11656105 -0.1266376 ]
 [-0.1256163  -0.11362593 -0.11749333]
 [-0.12632993 -0.11383588 -0.11566779]
 [-0.12833809 -0.11492631 -0.11234966]
 [-0.13178513 -0.12248707 -0.12171967]
 [-0.13373721 -0.12863282 -0.13057851]
 [-0.1299742  -0.1376086  -0.14874493]
 [-0.12827238 -0.14342192 -0.15947593]
 [-0.12708845 -0.1478742  -0.16866315]
 [-0.1301788  -0.1570965  -0.18169926]
 [-0.13091966 -0.16530914 -0.19477773]
 [-0.13730213 -0.1815317  -0.22273548]
 [-0.1438166  -0.18947136 -0.22785989]
 [-0.1480719  -0.19393226 -0.22957929]
 [-0.15465134 -0.20817727 -0.25143778]
 [-0.15870127 -0.21558819 -0.26058127]
 [-0.15963738 -0.21536902 -0.25798498]
 [-0.16000958 -0.21642727 -0.26053415]
 [-0.16109961 -0.21512893 -0.2563125 ]
 [-0.16079801 -0.21326534 -0.25301673]]
Debug: Final feature array shape: (27, 36)
Gesture test_female.mp4_segment_1_Gesture_0.13_1.23: R hand showed more movement
Debug: Landmarks shape is (14, 33, 3)
Debug: Extracting keypoint left_shoulder at index 11
Debug: Data for keypoint left_shoulder: [[-0.02416059 -0.16953638 -0.22191159]
 [-0.0213494  -0.15953241 -0.20088688]
 [-0.01959065 -0.15284959 -0.18641845]
 [-0.01877943 -0.14871792 -0.17719415]
 [-0.01878678 -0.14727772 -0.17326367]
 [-0.01924407 -0.14716045 -0.17226628]
 [-0.01892369 -0.14784397 -0.17421068]
 [-0.01710139 -0.14799632 -0.17639547]
 [-0.01445177 -0.14809271 -0.1793678 ]
 [-0.01402202 -0.14764606 -0.17948596]
 [-0.01397668 -0.14837666 -0.18129766]
 [-0.01412288 -0.14932381 -0.18343518]
 [-0.01414873 -0.15219338 -0.19022295]
 [-0.01345536 -0.15261489 -0.19181089]]
Debug: Extracting keypoint left_elbow at index 13
Debug: Data for keypoint left_elbow: [[ 0.07640106 -0.06810156 -0.16524815]
 [ 0.07628963 -0.06158777 -0.14676457]
 [ 0.07568628 -0.05591847 -0.12937068]
 [ 0.07582472 -0.05124622 -0.11617039]
 [ 0.07487256 -0.04769947 -0.10362243]
 [ 0.07350683 -0.0448281  -0.09273557]
 [ 0.07316813 -0.04448326 -0.09060832]
 [ 0.07368729 -0.04837522 -0.10088001]
 [ 0.07722523 -0.04653462 -0.10060837]
 [ 0.07905163 -0.04456977 -0.09854992]
 [ 0.08009553 -0.04399591 -0.09840255]
 [ 0.08081646 -0.04325847 -0.09820271]
 [ 0.08140876 -0.04316132 -0.09868035]
 [ 0.08203674 -0.04337583 -0.09999344]]
Debug: Extracting keypoint left_wrist at index 15
Debug: Data for keypoint left_wrist: [[ 0.08113088 -0.02065929 -0.12954184]
 [ 0.07561567 -0.02471525 -0.12416581]
 [ 0.07522436 -0.01902555 -0.10528534]
 [ 0.07574196 -0.01320427 -0.08837644]
 [ 0.0784554  -0.00362586 -0.06573994]
 [ 0.08044085  0.00718014 -0.0396358 ]
 [ 0.08348588  0.00960669 -0.03593024]
 [ 0.08645932  0.00339592 -0.05408606]
 [ 0.09236438  0.00860509 -0.0477806 ]
 [ 0.09271277  0.01166681 -0.04186881]
 [ 0.0930362   0.0137387  -0.03815187]
 [ 0.09272765  0.01345904 -0.03865869]
 [ 0.09223049  0.01157962 -0.04309948]
 [ 0.09213654  0.01084234 -0.04509267]]
Debug: Extracting keypoint right_shoulder at index 12
Debug: Data for keypoint right_shoulder: [[-0.24893574 -0.27146884 -0.22352172]
 [-0.24716328 -0.26333299 -0.20155343]
 [-0.24571049 -0.25905445 -0.18902458]
 [-0.24584362 -0.25737014 -0.18278151]
 [-0.2464263  -0.25741127 -0.18044646]
 [-0.24569652 -0.25632426 -0.17836291]
 [-0.24265039 -0.2556921  -0.18047948]
 [-0.23930661 -0.25508585 -0.18274623]
 [-0.23502975 -0.25508785 -0.18730007]
 [-0.23379674 -0.25378108 -0.18677144]
 [-0.23246391 -0.2533728  -0.1871882 ]
 [-0.23145446 -0.253353   -0.18822525]
 [-0.23038198 -0.25533398 -0.19406137]
 [-0.22775077 -0.25448731 -0.1947511 ]]
Debug: Extracting keypoint right_elbow at index 14
Debug: Data for keypoint right_elbow: [[-0.19280502 -0.17423021 -0.1609542 ]
 [-0.19536437 -0.16666178 -0.13239138]
 [-0.19708891 -0.16442348 -0.12072634]
 [-0.19859897 -0.16524796 -0.11868678]
 [-0.19845258 -0.16543838 -0.11833134]
 [-0.19621516 -0.16143464 -0.11176853]
 [-0.19313753 -0.16210428 -0.11718182]
 [-0.18976746 -0.16403772 -0.12557653]
 [-0.18410901 -0.16723719 -0.13960866]
 [-0.18335519 -0.16830483 -0.14502349]
 [-0.18258684 -0.17031637 -0.15107367]
 [-0.18152873 -0.17078598 -0.15347718]
 [-0.18039385 -0.17313615 -0.16026393]
 [-0.17776678 -0.17223275 -0.16083604]]
Debug: Extracting keypoint right_wrist at index 16
Debug: Data for keypoint right_wrist: [[-0.1165074  -0.12680502 -0.1789625 ]
 [-0.12478505 -0.1259954  -0.15449527]
 [-0.12950552 -0.1277701  -0.14622638]
 [-0.13472993 -0.13568676 -0.15326994]
 [-0.13499963 -0.14153509 -0.16012818]
 [-0.1342388  -0.14044298 -0.15369382]
 [-0.13210312 -0.14301089 -0.15771006]
 [-0.13714985 -0.16423421 -0.19652967]
 [-0.13452231 -0.17527101 -0.22069986]
 [-0.14189286 -0.1875319  -0.23463812]
 [-0.14715914 -0.19635837 -0.24599831]
 [-0.15190939 -0.2020625  -0.24998939]
 [-0.15627507 -0.2095103  -0.25937107]
 [-0.15896122 -0.21341561 -0.26215332]]
Debug: Final feature array shape: (14, 36)
Gesture test_female.mp4_segment_1_Gesture_0.50_1.07: R hand showed more movement
Debug: Landmarks shape is (22, 33, 3)
Debug: Extracting keypoint left_shoulder at index 11
Debug: Data for keypoint left_shoulder: [[-0.02077563 -0.15101955 -0.17602541]
 [-0.02276863 -0.15573483 -0.18515212]
 [-0.02282298 -0.1583483  -0.19111349]
 [-0.02214811 -0.16004573 -0.19586938]
 [-0.0213375  -0.16018414 -0.19733665]
 [-0.02122164 -0.16019304 -0.19762   ]
 [-0.02135191 -0.15987667 -0.1967008 ]
 [-0.02263061 -0.16155006 -0.19947423]
 [-0.02515777 -0.16248917 -0.19900339]
 [-0.02565594 -0.16313535 -0.20006929]
 [-0.0263094  -0.16450487 -0.20285988]
 [-0.02751301 -0.16563575 -0.20435192]
 [-0.02731049 -0.16519239 -0.20363859]
 [-0.02636485 -0.1614957  -0.19566858]
 [-0.02654174 -0.15978248 -0.19134631]
 [-0.02685209 -0.15695243 -0.18391592]
 [-0.02897629 -0.15708102 -0.18120477]
 [-0.02987694 -0.1580629  -0.18250787]
 [-0.03028008 -0.15805442 -0.18209788]
 [-0.03202919 -0.1594059  -0.18405465]
 [-0.03204097 -0.15871877 -0.1835722 ]
 [-0.03184093 -0.15892487 -0.18534185]]
Debug: Extracting keypoint left_elbow at index 13
Debug: Data for keypoint left_elbow: [[ 0.07264392 -0.05674107 -0.12314807]
 [ 0.07156363 -0.05597328 -0.11879601]
 [ 0.07226384 -0.05491661 -0.11542018]
 [ 0.07390475 -0.05408983 -0.1146597 ]
 [ 0.07553666 -0.05308965 -0.11361446]
 [ 0.07666035 -0.05219545 -0.11230701]
 [ 0.07651439 -0.05229538 -0.11133158]
 [ 0.07572198 -0.05451818 -0.11586383]
 [ 0.07295876 -0.05601177 -0.11653796]
 [ 0.07163111 -0.05862745 -0.12205166]
 [ 0.06965478 -0.06118574 -0.12692788]
 [ 0.06839098 -0.06246848 -0.12919264]
 [ 0.06851759 -0.06146106 -0.12719944]
 [ 0.06926782 -0.0577464  -0.1189503 ]
 [ 0.0681887  -0.05657571 -0.11502146]
 [ 0.06765011 -0.05559519 -0.11179627]
 [ 0.06479397 -0.05733499 -0.11256594]
 [ 0.06207659 -0.06075836 -0.1182975 ]
 [ 0.06206112 -0.0609283  -0.11926126]
 [ 0.06290388 -0.06233773 -0.12641828]
 [ 0.06475996 -0.06056157 -0.12725225]
 [ 0.06512584 -0.06142693 -0.13110408]]
Debug: Extracting keypoint left_wrist at index 15
Debug: Data for keypoint left_wrist: [[ 0.07042155 -0.02593141 -0.10516018]
 [ 0.06905142 -0.01449386 -0.07459631]
 [ 0.06919192 -0.01092491 -0.06408097]
 [ 0.07028674 -0.00908717 -0.05998409]
 [ 0.07177827 -0.00763917 -0.05758884]
 [ 0.07279771 -0.00491259 -0.05222762]
 [ 0.07283891 -0.00562933 -0.05374314]
 [ 0.07172376 -0.00658322 -0.05495781]
 [ 0.06752484 -0.00961758 -0.0580429 ]
 [ 0.06511948 -0.01573844 -0.07071235]
 [ 0.06240093 -0.01929409 -0.07709509]
 [ 0.06036082 -0.02172152 -0.08118377]
 [ 0.0612445  -0.01846813 -0.07435048]
 [ 0.0618783  -0.01546464 -0.06750691]
 [ 0.06031666 -0.01490965 -0.06456313]
 [ 0.05892298 -0.01559931 -0.06468155]
 [ 0.05690873 -0.01755827 -0.06705589]
 [ 0.05441697 -0.02524965 -0.08383034]
 [ 0.05479701 -0.02674194 -0.08873391]
 [ 0.05515402 -0.02965224 -0.09981854]
 [ 0.05416652 -0.02958155 -0.10119368]
 [ 0.05467708 -0.02969335 -0.10361675]]
Debug: Extracting keypoint right_shoulder at index 12
Debug: Data for keypoint right_shoulder: [[-0.24445343 -0.25520428 -0.17804936]
 [-0.2431012  -0.25747788 -0.18311238]
 [-0.23967624 -0.25907781 -0.18848078]
 [-0.23640157 -0.25922219 -0.19108246]
 [-0.23405672 -0.25889672 -0.19214538]
 [-0.23312277 -0.25861658 -0.1922845 ]
 [-0.23322488 -0.25870488 -0.19222536]
 [-0.2337858  -0.25983938 -0.19441646]
 [-0.23448744 -0.26001169 -0.1941554 ]
 [-0.23486789 -0.2609296  -0.19592003]
 [-0.23547875 -0.26224376 -0.19845942]
 [-0.23687398 -0.26336689 -0.1997595 ]
 [-0.23696142 -0.26330295 -0.19947127]
 [-0.23677324 -0.26049586 -0.1924667 ]
 [-0.23689883 -0.25842965 -0.18735709]
 [-0.23667043 -0.25480167 -0.17886611]
 [-0.2379948  -0.25389801 -0.17506412]
 [-0.23837619 -0.25461327 -0.17641298]
 [-0.23828027 -0.25455334 -0.17676224]
 [-0.238258   -0.25508989 -0.18033756]
 [-0.23794856 -0.25382475 -0.17928212]
 [-0.23734217 -0.25334835 -0.18041323]]
Debug: Extracting keypoint right_elbow at index 14
Debug: Data for keypoint right_elbow: [[-0.18250848 -0.16009497 -0.12383285]
 [-0.18400565 -0.15671549 -0.11095124]
 [-0.18106379 -0.15550956 -0.11003219]
 [-0.17889656 -0.15480404 -0.11026361]
 [-0.17746726 -0.15386711 -0.10939567]
 [-0.1774875  -0.15267467 -0.1061269 ]
 [-0.17809344 -0.15066862 -0.09949797]
 [-0.17938388 -0.15205707 -0.10116192]
 [-0.18234053 -0.15379183 -0.10188443]
 [-0.18297558 -0.15455614 -0.10285552]
 [-0.18380358 -0.15617322 -0.10587461]
 [-0.18548604 -0.15773235 -0.10783476]
 [-0.18608461 -0.15801744 -0.10779849]
 [-0.18642171 -0.15661319 -0.10347628]
 [-0.18741778 -0.15630491 -0.10157867]
 [-0.18753578 -0.15428387 -0.09625336]
 [-0.18869166 -0.15467392 -0.09529843]
 [-0.18899921 -0.15773844 -0.10231256]
 [-0.18883035 -0.15773818 -0.10262522]
 [-0.18856735 -0.16193675 -0.11493803]
 [-0.18807646 -0.16125003 -0.11442595]
 [-0.18846993 -0.16318883 -0.11900634]]
Debug: Extracting keypoint right_wrist at index 16
Debug: Data for keypoint right_wrist: [[-0.11846745 -0.13804159 -0.17539912]
 [-0.1208547  -0.12383043 -0.13207565]
 [-0.12530652 -0.13143191 -0.13976116]
 [-0.12647269 -0.1342733  -0.14425553]
 [-0.12679253 -0.13499943 -0.14542885]
 [-0.12724475 -0.13026927 -0.13409885]
 [-0.12671293 -0.12259127 -0.1166443 ]
 [-0.12812268 -0.12107975 -0.11399038]
 [-0.13067138 -0.11972258 -0.11059644]
 [-0.1308024  -0.12058209 -0.1145691 ]
 [-0.13006125 -0.12036308 -0.11646386]
 [-0.13154069 -0.12180874 -0.11842404]
 [-0.13140053 -0.12166867 -0.11790415]
 [-0.1315221  -0.12100258 -0.11542374]
 [-0.13144279 -0.12085513 -0.11511478]
 [-0.13077049 -0.1182818  -0.10966033]
 [-0.13060283 -0.1181075  -0.10947205]
 [-0.12641446 -0.11788519 -0.11609219]
 [-0.12360419 -0.11511623 -0.1146885 ]
 [-0.12121442 -0.118004   -0.12783735]
 [-0.12025662 -0.1167955  -0.12710284]
 [-0.11960645 -0.117911   -0.13161746]]
Debug: Final feature array shape: (22, 36)
Gesture test_female.mp4_segment_2_Gesture_2.34_3.24: L hand showed more movement
Debug: Landmarks shape is (21, 33, 3)
Debug: Extracting keypoint left_shoulder at index 11
Debug: Data for keypoint left_shoulder: [[-0.02286874 -0.15250272 -0.17846694]
 [-0.02042426 -0.15359988 -0.18351971]
 [-0.01964657 -0.15782271 -0.19433181]
 [-0.01863478 -0.15782016 -0.19546302]
 [-0.01860136 -0.15730317 -0.19426144]
 [-0.01943188 -0.15975744 -0.19926302]
 [-0.02076886 -0.16009525 -0.19839096]
 [-0.02297974 -0.16049878 -0.19631551]
 [-0.02469109 -0.16153671 -0.19656102]
 [-0.02540356 -0.1618049  -0.19638898]
 [-0.02653249 -0.16185095 -0.19527616]
 [-0.02636118 -0.16148702 -0.19463765]
 [-0.02606419 -0.16089378 -0.19352011]
 [-0.02578236 -0.15961032 -0.19074505]
 [-0.02588553 -0.1576714  -0.18599395]
 [-0.02818302 -0.15758195 -0.18345893]
 [-0.03087425 -0.16189045 -0.1911039 ]
 [-0.03255955 -0.16366551 -0.19379795]
 [-0.03196612 -0.16161973 -0.18993648]
 [-0.03178994 -0.1613362  -0.18948048]
 [-0.03165859 -0.16115421 -0.18920945]]
Debug: Extracting keypoint left_elbow at index 13
Debug: Data for keypoint left_elbow: [[ 0.0728151  -0.05315497 -0.11392425]
 [ 0.07513406 -0.05109673 -0.11044204]
 [ 0.07631852 -0.0510438  -0.11085303]
 [ 0.07715304 -0.05018469 -0.10933757]
 [ 0.07962839 -0.04781787 -0.10557676]
 [ 0.07928984 -0.04911012 -0.10802837]
 [ 0.07851426 -0.05062405 -0.11060852]
 [ 0.07513192 -0.05270685 -0.11158978]
 [ 0.07261762 -0.05427258 -0.1126544 ]
 [ 0.07181711 -0.05525322 -0.11423273]
 [ 0.06971248 -0.05676184 -0.1159449 ]
 [ 0.07015345 -0.05607316 -0.11503941]
 [ 0.07032132 -0.05590301 -0.11495487]
 [ 0.07048558 -0.05551969 -0.11429635]
 [ 0.07025847 -0.05533751 -0.11364633]
 [ 0.06899148 -0.05550404 -0.11278364]
 [ 0.06550781 -0.06018659 -0.12135926]
 [ 0.06441455 -0.06289911 -0.12808163]
 [ 0.06521914 -0.06102474 -0.12572922]
 [ 0.06576876 -0.0600817  -0.12448795]
 [ 0.06634237 -0.05989189 -0.12526489]]
Debug: Extracting keypoint left_wrist at index 15
Debug: Data for keypoint left_wrist: [[ 0.0742181  -0.01408893 -0.08346643]
 [ 0.07538835 -0.00377126 -0.05779792]
 [ 0.07450144 -0.00331537 -0.05383175]
 [ 0.07507257 -0.00227502 -0.05064777]
 [ 0.07664185  0.00178824 -0.04207234]
 [ 0.07657143 -0.00022327 -0.0467974 ]
 [ 0.07536807 -0.00129447 -0.04847772]
 [ 0.07128702 -0.00402291 -0.05104913]
 [ 0.06808553 -0.00616791 -0.05304275]
 [ 0.06645202 -0.00931869 -0.05915207]
 [ 0.0635561  -0.01380103 -0.06727615]
 [ 0.06408964 -0.01275631 -0.06538199]
 [ 0.06428246 -0.01307371 -0.06638559]
 [ 0.06443427 -0.01298164 -0.0663566 ]
 [ 0.06376552 -0.01330518 -0.06645908]
 [ 0.06313091 -0.01358094 -0.06648414]
 [ 0.05955126 -0.01966416 -0.07787387]
 [ 0.05906498 -0.0243577  -0.09048267]
 [ 0.06054825 -0.02140312 -0.08721552]
 [ 0.06120489 -0.01977293 -0.08461781]
 [ 0.06077154 -0.02198803 -0.0901254 ]]
Debug: Extracting keypoint right_shoulder at index 12
Debug: Data for keypoint right_shoulder: [[-0.25012005 -0.25729935 -0.18009719]
 [-0.23865065 -0.25407655 -0.18116913]
 [-0.23477727 -0.25549863 -0.18660608]
 [-0.23413507 -0.25636877 -0.18847903]
 [-0.23338062 -0.25610945 -0.18774423]

d:\Programs\Conda_packages\envs\envisionbetalight\lib\site-packages\umap\umap_.py:1780: UserWarning: using precomputed metric; inverse_transform will be unavailable
  warn("using precomputed metric; inverse_transform will be unavailable")

Analysis results: {'distance_matrix': 'd:\\Research_projects\\usingenvisionhgdetector\\output\\analysis\\dtw_distances.csv', 'kinematic_features': 'd:\\Research_projects\\usingenvisionhgdetector\\output\\analysis\\kinematic_features.csv', 'visualization': 'd:\\Research_projects\\usingenvisionhgdetector\\output\\analysis\\gesture_visualization.csv'}

## Running the above code gives us the kinematic features and a dissimilarity DTW matrix

In [31]:
import pandas as pd
import os
# lets list the output
outputfiles = glob.glob(outputfolder + '/analysis/*')
for file in outputfiles:
    print(os.path.basename(file))

# load one of the predictions
csvfilessegments = glob.glob(outputfolder + '/analysis/kinematic_features.csv')
df = pd.read_csv(csvfilessegments[0])
df.head()

dtw_distances.csv
gesture_visualization.csv
kinematic_features.csv

,gesture_id,video_id,active_hand,space_use,mcneillian_max,mcneillian_mode,volume,max_height,duration,hold_count,...,hand_peak_speed,hand_mean_speed,hand_peak_acceleration,hand_peak_deceleration,hand_peak_jerk,elbow_peak_speed,elbow_mean_speed,elbow_peak_acceleration,elbow_peak_deceleration,elbow_peak_jerk
0,test_female.mp4_segment_1_Gesture_0.13_1.23,test,R,1,2,2,0.000649,2.719734,1.08,2,...,0.415878,0.192340,2.277804,0.050360,19.282979,0.120248,0.079381,0.987083,0.109988,11.464334
1,test_female.mp4_segment_1_Gesture_0.50_1.07,test,R,1,2,2,0.000430,2.706761,0.56,0,...,0.471949,0.248035,2.782987,0.478393,35.455300,0.176683,0.110604,1.827855,0.235981,22.895113
2,test_female.mp4_segment_2_Gesture_2.34_3.24,test,L,1,2,2,0.000024,0.000000,0.88,1,...,0.171867,0.094851,1.576741,0.089730,21.349347,0.074585,0.043239,0.930251,0.086323,14.709287
3,test_female.mp4_segment_2_Gesture_2.37_3.24,test,R,1,2,2,0.000044,2.477384,0.84,1,...,0.185567,0.083878,1.039056,0.084769,17.966591,0.108506,0.048278,1.014999,0.051772,15.341328
4,test_female.mp4_segment_3_Gesture_3.80_4.14,test,R,1,2,2,0.000002,2.462870,0.32,0,...,0.126205,0.071599,0.827005,0.044555,14.667753,0.103911,0.059782,0.664494,0.047701,11.938172

In [32]:
detector.prepare_gesture_dashboard(
    data_folder=analysis_folder
    )

Copying test_female.mp4_segment_1_Gesture_0.13_1.23_tracked.mp4 to assets folder...
Copying test_female.mp4_segment_2_Gesture_2.34_3.24_tracked.mp4 to assets folder...
Copying test_female.mp4_segment_3_Gesture_3.80_4.14_tracked.mp4 to assets folder...
Copying test_female.mp4_segment_4_Gesture_4.44_6.54_tracked.mp4 to assets folder...
Copying test_female.mp4_segment_5_Gesture_7.67_11.18_tracked.mp4 to assets folder...
Copying test_male.mp4_segment_1_Gesture_0.17_3.64_tracked.mp4 to assets folder...
Copying test_male.mp4_segment_2_Gesture_5.00_5.81_tracked.mp4 to assets folder...
Copying test_male.mp4_segment_3_Gesture_8.98_9.78_tracked.mp4 to assets folder...
Copying test_male.mp4_segment_4_Gesture_12.01_12.35_tracked.mp4 to assets folder...
Copying test_male.mp4_segment_5_Gesture_12.71_13.01_tracked.mp4 to assets folder...
Dashboard folders set up successfully:
- Assets folder: d:\Research_projects\usingenvisionhgdetector\output\assets
- Data folder: d:\Research_projects\usingenvisionhgdetector\output\analysis
- 19 videos in assets
Dashboard prepared for LIGHTGBM results
App dashboard copied to: d:\Research_projects\usingenvisionhgdetector\output\app.py
CSS file created at: d:\Research_projects\usingenvisionhgdetector\output\assets\styles.css
Run 'python app.py' to start the dashboard

# Running the app
Now in your terminal activate your envirnment, cd (change drive) to your output folder, and then activate the app. You can then copy the address in your chrome browser to access the app that is running.
```python
conda activate envision
cd [outputfolder]
python app.py
```

You app will look like this: 


<img src="Images/dashboard.gif"  width="300"/>

# Concluding remarks
It is important to test the accuracy of your classifier against some hand-labeled data that was not used to train your model on. We are preparing a preprint where we report this.